exports.ReportData_Structure = () => {
  return [
    {
      ID: "",
      ReqNo: "",
      CustFull: "",
      PatternReport: "",
      ReportOrder: "",
      SampleNo: "",
      GroupNameTS: "",
      SampleGroup: "",
      SampleType: "",
      SampleTank: "",
      SampleName: "",
      ProcessReportName: "",
      SamplingDate: "",
      CreateReportDate: "",
      ItemNo: "",
      ItemName: "",
      ItemReportName: "",
      StdFactor: "",
      StdMin: "",
      StdSymbol: "",
      StdMax: "",
      ControlRange: "",
      ResultIn: "",
      ResultReport: "",
      Evaluation: "",
      Incharge: "",
      SubLeader: "",
      SubLeaderTime: "",
      GL: "",
      GLTime: "",
      JP: "",
      JPTime: "",
      DGM: "",
      DGMTime: "",
      ReportCompleteDate: "",
      NextApprover: "",
      Comment1: "",
      Comment2: "",
      Comment3: "",
      Comment4: "",
      Comment5: "",
      Comment6: "",
      Comment7: "",
      Comment8: "",
      Comment9: "",
      Comment10: "",
    },
  ];
};
